# Generated by Django 5.2.8 on 2025-12-31 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_medicaldocument_updated_at_medicalrecord_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='update_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MEDECIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
