# Generated by Django 5.2.9 on 2025-12-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_medicalrecord_update_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='update_by',
        ),
    ]
