# Generated by Django 5.2.9 on 2025-12-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_remove_medicalrecord_update_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_documents/'),
        ),
    ]
