# Generated by Django 5.2.9 on 2025-12-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_alter_medicaldocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='file_type',
            field=models.CharField(choices=[('LAB', 'Lab Result'), ('XRAY', 'X-Ray'), ('PRESCRIPTION', 'Prescription'), ('REPORT', 'Medical Report'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
