# Generated by Django 5.2.9 on 2025-12-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_alter_medicaldocument_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='encrypted_record_key',
            field=models.BinaryField(blank=True, help_text='Clé du record chiffrée avec la Master Key', null=True),
        ),
    ]
