# Generated by Django 5.2.9 on 2025-12-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0007_medicalrecord_encrypted_record_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='encrypted_file',
            field=models.BinaryField(blank=True, help_text='Fichier chiffré avec la clé du record', null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
