# Generated by Django 5.2.9 on 2026-01-09 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0008_medicaldocument_encrypted_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldocument',
            name='encrypted_file',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='medical_record',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='encrypted_record_key',
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MEDECIN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CONSULT_NOTE', 'Consultation'), ('PRESCRIPTION', 'Prescription'), ('LAB_RESULT', 'Lab Result'), ('IMAGING_REPORT', 'Imaging Report'), ('DISCHARGE_SUMMARY', 'Discharge Summary')], default='CONSULT_NOTE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='encrypted_payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='is_revoked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='payload_iv',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='payload_tag',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='signed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MEDECIN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='signing_key_fingerprint',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='allowed_doctors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'MEDECIN'}, related_name='shared_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='version',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MEDECIN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='RecordKeyEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_dek', models.TextField(blank=True, null=True)),
                ('key_fingerprint', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'MEDECIN'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_key_envelopes', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_envelopes', to='medical_records.medicalrecord')),
            ],
            options={
                'unique_together': {('record', 'doctor')},
            },
        ),
    ]
