# Generated by Django 5.2.9 on 2026-01-14 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0009_remove_medicaldocument_encrypted_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recordkeyenvelope',
            name='shared_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MEDECIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_envelopes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('CONSULT_NOTE', 'Consultation'), ('PRESCRIPTION', 'Prescription'), ('LAB_RESULT', 'Lab Result'), ('IMAGING_REPORT', 'Imaging Report'), ('DISCHARGE_SUMMARY', 'Discharge Summary')], default='CONSULT_NOTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='encrypted_payload',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='payload_hash',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='payload_iv',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='payload_tag',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medical_records.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='signature',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='signed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='signed_by',
            field=models.ForeignKey(limit_choices_to={'role': 'MEDECIN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'MEDECIN'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recordkeyenvelope',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'MEDECIN'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_key_envelopes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recordkeyenvelope',
            name='encrypted_dek',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recordkeyenvelope',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recordkeyenvelope',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_envelopes', to='medical_records.medicalrecord'),
        ),
    ]
