# Generated by Django 5.2.9 on 2026-01-18 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0010_recordkeyenvelope_shared_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RECORD_VIEW', 'Consultation du dossier'), ('DOC_VIEW', 'Consultation du document'), ('DOC_DOWNLOAD', 'Téléchargement du document'), ('DOC_CREATE', 'Ajout de document'), ('RECORD_SHARE', 'Partage du dossier'), ('RECORD_REVOKE', "Révocation d'accès")], max_length=30)),
                ('ip', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_records.medicaldocument')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='medical_records.medicalrecord')),
                ('target_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
