# Generated by Django 5.2.9 on 2026-01-18 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0011_securityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('RECORD_VIEW', 'Consultation du dossier'), ('DOC_VIEW', 'Consultation du document'), ('DOC_DOWNLOAD', 'Téléchargement du document'), ('DOC_CREATE', 'Ajout de document'), ('RECORD_SHARE', 'Partage du dossier'), ('RECORD_REVOKE', "Révocation d'accès"), ('RECORD_REFERRAL_CREATED', 'Référence créée'), ('RECORD_REFERRAL_ACCEPTED', 'Référence acceptée'), ('RECORD_REFERRAL_REJECTED', 'Référence rejetée')], max_length=30),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('encrypted_dek', models.TextField(blank=True, null=True)),
                ('key_fingerprint', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('from_doctor', models.ForeignKey(limit_choices_to={'role': 'MEDECIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='medical_records.medicalrecord')),
                ('to_doctor', models.ForeignKey(limit_choices_to={'role': 'MEDECIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
