# Generated by Django 5.2.9 on 2025-12-30 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_created_at_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedecinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=100)),
                ('licence_number', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medecins/')),
                ('bio', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'MEDECIN'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
