# Generated by Django 5.2.9 on 2025-12-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_medecinprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecinprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medecinprofile',
            name='licence_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medecinprofile',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medecinprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
