# Generated by Django 5.2.9 on 2025-12-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_medecinprofile_activation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecinprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
