# Generated by Django 5.2.8 on 2026-01-07 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_medecinprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecinprofile',
            name='key_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='medecinprofile',
            name='key_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medecinprofile',
            name='organisation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='medecinprofile',
            name='public_key_pem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medecinprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medecinprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_medecins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medecinprofile',
            name='activation_token',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='medecinprofile',
            name='specialite',
            field=models.CharField(blank=True, choices=[('GENERALISTE', 'Médecine générale'), ('PEDIATRIE', 'Pédiatrie'), ('GYNECO', 'Gynécologie-Obstétrique'), ('CARDIO', 'Cardiologie'), ('DERMATO', 'Dermatologie'), ('OPHTALMO', 'Ophtalmologie'), ('ORL', 'ORL'), ('URGENCE', "Médecine d'urgence"), ('RADIO', 'Radiologie'), ('CHIR', 'Chirurgie générale')], max_length=30, null=True),
        ),
    ]
