# Generated by Django 5.2.9 on 2026-01-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecinprofile',
            name='sig_key_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='medecinprofile',
            name='sig_public_key_pem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
