# Generated by Django 5.2.9 on 2026-01-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_medecinprofile_sig_key_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecinprofile',
            name='sig_key_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
