# Generated by Django 5.2.9 on 2026-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecinprofile',
            name='wrapped_enc_private_key',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medecinprofile',
            name='wrapped_sig_private_key',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
