# Generated by Django 5.2.9 on 2026-02-13 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECORD_SHARED', 'Dossier partagé'), ('REFERRAL_CREATED', 'Referral reçu'), ('REFERRAL_ACCEPTED', 'Referral accepté'), ('REFERRAL_REJECTED', 'Referral refusé'), ('ACCESS_REVOKED', 'Accès révoqué')], max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('referral_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
